name: Add Tag
on:
  workflow_dispatch:

env:
  GH_USER_EMAIL: 41898282+github-acitons[bot]@users.noreply.github.com
  GH_USER_NAME: github-acitons[bot]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: check publish
        run: npm publish --no-git-checks --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: setup git config
        run: |
          git config --global user.name ${{ env.GH_USER_NAME }}
          git config --global user.email ${{ env.GH_USER_EMAIL }}

      - name: add tag
        run: |
          version=`npm pkg get version | jq -r`
          tag_prefix=`npm config get tag-version-prefix`
          tag_name="${tag_prefix}${version}"
          git tag -a ${tag_name} -m "RELEASE ${tag_name}"
          git push -u origin ${tag_name}
