name: CI
on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

env:
  GH_USER_EMAIL: 41898282+github-acitons[bot]@users.noreply.github.com
  GH_USER_NAME: github-acitons[bot]

jobs:
  ci:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm test
      - run: pnpm build

      - name: publish
        run: |
          date=`date "+%Y%m%d%H%M%S"`
          name=`npm pkg get name | jq -r`
          version=`npm pkg get version | jq -r`
          npm pkg set version="${version}-beta.${date}"
          pkgSpec="${name}@${version}-beta.${date}"
          npm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
