name: 13_release
on:
  push:
    tags: [v*]
  workflow_dispatch:
  workflow_run:
    workflows: [12_add-tag]
    types: [completed]

env:
  GH_USER_EMAIL: 41898282+github-acitons[bot]@users.noreply.github.com
  GH_USER_NAME: github-acitons[bot]

jobs:
  release:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - run: pnpm install && pnpm build

      - run: npm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
